Repository flux-framework/PerfFlowAspect, pull requests merged in 2022-02, with the labels that each got.

#35 setup.py: remove package_dir field
  .github/workflows/github-actions.yml
  src/python/setup.py
Labels: status-ready-for-review

#33 Add mergify config file
  .github/workflows/github-actions.yml
  .mergify.yml
Labels: status-ready-for-review

#37 bump heading of license from level 4 to 3 in README
  README.md
Labels: status-ready-for-review, style

#34 Add black and flake8 configs
  .github/workflows/github-actions.yml
  README.md
  src/python/.flake8
  src/python/perfflowaspect/advice_chrome.py
  src/python/perfflowaspect/aspect.py
  src/python/pyproject.toml
  src/python/setup.py
  src/python/test/smoketest.py
  src/python/test/smoketest_MT.py
  src/python/test/smoketest_future.py
  src/python/test/smoketest_future2.py
  src/python/test/smoketest_future_direct.py
  src/python/test/smoketest_future_incorrect.py
Labels: status-ready-for-review, style

#27 Add read the docs support
  .readthedocs.yml
  README.md
  docs/Annotations.rst
  docs/BuildingPerfFlowAspect.rst
  docs/Licenses.rst
  docs/PerfFlowAspectDevel.rst
  docs/QuickStart.rst
  docs/Releases.rst
  docs/UpcomingFeatures.rst
  docs/conf.py
  docs/index.rst
Labels: documentation, status-merge-when-passing

#36 Use qualified name in logging performance event data
  src/python/perfflowaspect/advice_chrome.py
Labels: enhancement, status-ready-for-review

#42 update copyright year to 2022
  docs/Annotations.rst
  docs/BuildingPerfFlowAspect.rst
  docs/Licenses.rst
  docs/PerfFlowAspectDevel.rst
  docs/QuickStart.rst
  docs/Releases.rst
  docs/UpcomingFeatures.rst
  docs/conf.py
  docs/index.rst
  src/c/parser/lex.l
  src/c/parser/parser.y
  src/c/parser/perfflow_parser.cpp
  src/c/parser/perfflow_parser.hpp
  src/c/parser/test/anno_parse_test.cpp
  src/c/parser/test/anno_validate_test.cpp
  src/c/runtime/advice_base.hpp
  src/c/runtime/advice_chrome_tracing.cpp
  src/c/runtime/advice_chrome_tracing.hpp
  src/c/runtime/advice_dispatcher.cpp
  src/c/runtime/advice_dispatcher.hpp
  src/c/runtime/perfflow_runtime.cpp
  src/c/test/smoketest.cpp
  src/c/test/smoketest2.cpp
  src/c/weaver/weave/perfflow_weave.cpp
  src/c/weaver/weave/perfflow_weave.hpp
  src/python/perfflowaspect/advice_chrome.py
  src/python/perfflowaspect/advice_dispatch.py
  src/python/perfflowaspect/aspect.py
  src/python/perfflowaspect/aspect_base.py
  src/python/setup.py
Labels: status-ready-for-review, status-merge-when-passing

#43 Revert "update copyright year to 2022"
  docs/Annotations.rst
  docs/BuildingPerfFlowAspect.rst
  docs/Licenses.rst
  docs/PerfFlowAspectDevel.rst
  docs/QuickStart.rst
  docs/Releases.rst
  docs/UpcomingFeatures.rst
  docs/conf.py
  docs/index.rst
  src/c/parser/lex.l
  src/c/parser/parser.y
  src/c/parser/perfflow_parser.cpp
  src/c/parser/perfflow_parser.hpp
  src/c/parser/test/anno_parse_test.cpp
  src/c/parser/test/anno_validate_test.cpp
  src/c/runtime/advice_base.hpp
  src/c/runtime/advice_chrome_tracing.cpp
  src/c/runtime/advice_chrome_tracing.hpp
  src/c/runtime/advice_dispatcher.cpp
  src/c/runtime/advice_dispatcher.hpp
  src/c/runtime/perfflow_runtime.cpp
  src/c/test/smoketest.cpp
  src/c/test/smoketest2.cpp
  src/c/weaver/weave/perfflow_weave.cpp
  src/c/weaver/weave/perfflow_weave.hpp
  src/python/perfflowaspect/advice_chrome.py
  src/python/perfflowaspect/advice_dispatch.py
  src/python/perfflowaspect/aspect.py
  src/python/perfflowaspect/aspect_base.py
  src/python/setup.py
Labels: status-merge-when-passing

#44 fix docs badge in README
  README.md
Labels: status-ready-for-review
