Repository flux-framework/PerfFlowAspect, pull requests merged in 2023-05, with the labels that each got.

#96 docs: add info for visualization
  docs/BasicTutorial.rst
  docs/QuickStart.rst
  docs/images/vis1.png
  docs/images/vis2.png
  docs/index.rst
Labels: documentation, status-work-in-progress

#102 Python: Async Events need an ID to work with Perfetto
  src/python/perfflowaspect/advice_chrome.py
Labels: status-ready-to-merge

#109 Update docs for v0.1
  docs/BasicTutorial.rst
  docs/BuildingPerfFlowAspect.rst
  docs/UpcomingFeatures.rst
  docs/index.rst
  docs/ppts/PerfFlowAspectTutorialSlides.pdf
  docs/ppts/PerfFlowAspectTutorialSlides.pptx
Labels: documentation, status-ready-for-review
