Repository flux-framework/PerfFlowAspect, pull requests merged in 2023-03, with the labels that each got.

#45 Python: Add optional chrome advice to use X events for around events.
  .gitignore
  src/python/perfflowaspect/advice_chrome.py
  src/python/test/t0001-pybinding-basic.t
Labels: enhancement, status-ready-for-review

#90 C: Add optional chrome advice to use X events for around events.
  src/c/runtime/advice_chrome_tracing.cpp
  src/c/runtime/advice_chrome_tracing.hpp
  src/c/test/t0001-cbinding-basic.t.in
Labels: enhancement

#91 add initial gitlab config
  .gitlab-ci.yml
  src/c/test/t0001-cbinding-basic.t.in
  src/python/test/t0001-pybinding-basic.t
Labels: status-ready-for-review
